### ISSUE TITLE
Incomplete Address

### ISSUE THREAD

**Issue by kaitlingee** [NorthIsUp/shimmy.town#9]
Throughout the site, Shimmytown (Verdi Club) address is considered incomplete, lacking the road name, "Street".

EXAMPLE 1:
<img width="379" alt="screen shot 2017-10-03 at 9 29 57 pm" src="https://user-images.githubusercontent.com/32504190/31160033-1312a8d2-a882-11e7-9313-6c0ec34ca8c1.png">
EXAMPLE 2:
<img width="174" alt="screen shot 2017-10-03 at 9 34 43 pm" src="https://user-images.githubusercontent.com/32504190/31160092-b0770992-a882-11e7-8c7d-9997d36f10a9.png">

As seen in the above examples, the Shimmytown address currently only reads, "2424 Mariposa".

**Comment by NorthIsUp** [comment]
fixed!
